# Optional Prometheus HTTPS config snippet for production
# See https://prometheus.io/docs/prometheus/latest/configuration/configuration/
# This snippet should be included in your main prometheus.yml under the 'web' section

web:
  tls_server_config:
    cert_file: /etc/prometheus/certs/server.crt
    key_file: /etc/prometheus/certs/server.key
    client_auth_type: "RequireAndVerifyClientCert"
    client_ca_file: /etc/prometheus/certs/ca.crt
#  http2: true
#  min_version: TLS12
